### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by JaimeObregon** [slashdotdash/jekyll-lunr-js-search#108]
I know this has been already discussed at least in #84, #74, #58, #16, the point being that Lunr.js itself doesn't support other language than English, but there is a popular side-project, [MihaiValentin/lunr-languages](https://github.com/MihaiValentin/lunr-languages), which does the dirty work of providing stemmers for quite a lot different languages.

With that in hand, it should be feasible, and probably simple, to modify `jekyll-lunr-js-search` to add support for these other languages, a task I would gently contribute by myself if I had enough skills in Ruby. Thank you.

**Comment by slashdotdash** [comment]
Duplicated by #119.
