### ISSUE TITLE
Conflict with newer json

### ISSUE THREAD

**Issue by scottcwilson** [slashdotdash/jekyll-lunr-js-search#114]
I'm getting 

Dependency Error: Yikes! It looks like you don't have jekyll-lunr-js-search or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'Unable to activate jekyll-lunr-js-search-3.2.0, because json-2.0.2 conflicts with json (~> 1.8)' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!

How do I fix this?

**Comment by slashdotdash** [comment]
@scottcwilson I've encountered a similar error trying to install locally. It's dependency hell. 

When I can get it working I'll let you know.

**Comment by slashdotdash** [comment]
I've just upgraded all of the Ruby gem and JavaScript dependencies. 

Published [jekyll-lunr-js-search](https://rubygems.org/gems/jekyll-lunr-js-search) v3.3.0 to Ruby gems. Hopefully that will resolve your problem.
