### ISSUE TITLE
How do you compare this to Elasticlunr.js?

### ISSUE THREAD

**Issue by d3netxer** [slashdotdash/jekyll-lunr-js-search#116]

**Comment by slashdotdash** [comment]
From a brief read through of the documentation for [elasticlunr.js](https://github.com/weixsong/elasticlunr.js) it looks like a fork and improvement of lunr.js.

The following two points stood as a benefit over lunr.js:

> Elasticlunr.js removed TokenCorpus and Vector from lunr.js, by using combined model there is no need to compute the vector of a document and query string to compute similarity of query and matched document, this improve the search speed significantly.

> The index size is about half size of lunr.js index file.
