### ISSUE TITLE
[RFE] Consider switching from therubyracer to execJs

### ISSUE THREAD

**Issue by frantisekz** [slashdotdash/jekyll-lunr-js-search#123]
It would be nice not to depend on therubyracer (which is using ancient libv8), but on execJs[0] instead (which can make use of therubyracer, but also a lot of other JS implementations (mini_racer for example)).

[0] https://github.com/rails/execjs

**Comment by slashdotdash** [comment]
A pull request to make this change would be gladly accepted.
