### ISSUE TITLE
New Jekyll Collections

### ISSUE THREAD

**Issue by zachlyon** [slashdotdash/jekyll-lunr-js-search#28]
Will this support Jekyll 2 Collections? They don't appear to be getting indexed, Posts and  Pages show up just fine.

**Comment by iloveip** [comment]
Hello,

Does this plugin support Jekyll Collections now?

**Comment by kojoru** [comment]
I guess we can close that now?

**Comment by slashdotdash** [comment]
Fixed thanks to @kojoru via #69.
