### ISSUE TITLE
plugin throwing layout errors in Jekyll 2.2.0

### ISSUE THREAD

**Issue by dcac** [slashdotdash/jekyll-lunr-js-search#34]
Now that Jekyll returns errors for any missing layouts, jekyll-lunr.js seems to be returning them for every page its indexing.

Things build fine, but i'd like to not see a list of warnings for every build.

is there some way to turn these off/hide them/fix this?

Thanks.

**Comment by tomjohnson1492** [comment]
I'm having this problem as well. 

```
        Lunr: Creating search index...
     Build Warning: Layout 'default' requested in content/acme/archive.html does not exist.
```

The default.html layout exists in my _layouts folder.

**Comment by llbbl** [comment]
Hey ... 

We were having the following warnings every time we ran jekyll build:
```
Build Warning: Layout 'post'
Build Warning: Layout 'nil' requested in categories/site/atom.xml does not exist.
```

The change from @stephenhowells fixed it for me. We are using a slightly different (older) plugin than the one in the repo, but some of the parts are still similar I think. 

changed:
```
      def render(item)
        item.render({}, @site.site_payload)
        doc = Nokogiri::HTML(item.output)
        paragraphs = doc.search('//text()').map {|t| t.content }
        paragraphs = paragraphs.join(" ").gsub("\r", " ").gsub("\n", " ").gsub("\t", " ").gsub(/\s+/, " ")
      end
```

to:
```
      def render(item)
        item.render(@site.layouts, @site.site_payload)
        doc = Nokogiri::HTML(item.output)
        paragraphs = doc.search('//text()').map {|t| t.content }
        paragraphs = paragraphs.join(" ").gsub("\r", " ").gsub("\n", " ").gsub("\t", " ").gsub(/\s+/, " ")
      end
```
