### ISSUE TITLE
Latest code throws Error:  undefined local variable or method `__dir__'

### ISSUE THREAD

**Issue by larryhynes** [slashdotdash/jekyll-lunr-js-search#49]
Hi

I just pulled down the latest code from the repo and Jekyll is refusing to build, saying:

```
jekyll 2.5.2 | Error:  undefined local variable or method `__dir__' for #<Jekyll::LunrJsSearch::Indexer:0x007fe898899710 @js_dir="js">
```

which I'm finding a little odd! ;) All was working fine, I updated my `bundle` and installed libv8 OK, not sure where to start looking for a solution to this.

**Comment by hdgarrood** [comment]
The issue appears to be that Lunr is using a trie-like structure in the index (at the key `tokenStore.root`), which means it could be arbitrarily deeply nested. I think the correct solution is to pass `:max_nesting => false`, which incidentally is working for me at the moment.

**Comment by hdgarrood** [comment]
Oh wait, disabling the maximum nesting check works fine in `irb`, but not in the plugin. uggggggg rubby. Using `JSON.parse!` fails the same way too.

**Comment by slashdotdash** [comment]
I've just pushed an updated version of the gem that fixes the `__dir__` issue.

https://rubygems.org/gems/jekyll-lunr-js-search/versions/0.2.1

**Comment by luckyluke007** [comment]
I got nesting error too...``` :max_nesting => false``` doesn't work for me..
