### ISSUE TITLE
search.js.map

### ISSUE THREAD

**Issue by Romiko** [slashdotdash/jekyll-lunr-js-search#51]
Hi,

I am using the gem install version (Not using Bower). I notice the search page has the following network request which does not exist, any ideas why? This happens on my search page via the script 

<script src="/js/search.min.js" type="text/javascript" charset="utf-8"></script>

Request URL:http://localhost:4000/js/search.js.map
Request Method:GET
Status Code:404 Not Found
Request Headersview source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Host:localhost:4000
Referer:http://localhost:4000/search/index.html?q=buffalo

**Comment by atuleu** [comment]
Same for me. and then search does not work

**Comment by trevorsenior** [comment]
As a temporary fix you can remove the following line at the end of the minified output: 

```javascript
//# sourceMappingURL=search.js.map
```

**Comment by alexbaldwin** [comment]
:+1:

**Comment by ccsastro** [comment]
Yes,  temporary fix works.

**Comment by blimey85** [comment]
```*.map``` is an UnMinified version of Minified files that can be edited within Chrome Developer Tools. It's not required for function and removing the reference at the bottom of the Minified file is fine.

**Comment by Romiko** [comment]
Indeed. I have it working nicely now :)



On Thu, May 28, 2015 at 4:38 AM, Gary Traffanstedt <notifications@github.com
> wrote:

> *.map is an UnMinified version of Minified files that can be edited
> within Chrome Developer Tools. It's not required for function and removing
> the reference at the bottom of the Minified file is fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/slashdotdash/jekyll-lunr-js-search/issues/51#issuecomment-106027191>
> .
>



-- 
Romiko Derbynew
*Mobile:* +61 4000 90251
*Email:* romikov@gmail.com

*Website: *http://rangerrom.com
*Blog: *http://rangerrom.com/blog

**Comment by lorenzschmid** [comment]
Still is a thing. Thanks for the hint.
