### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by Romiko** [slashdotdash/jekyll-lunr-js-search#52]
HI

I installed the Gem. 
My search page is /search/index.html
---
layout: page
title: Search - Ranger Rom
keywords: Search wildlife  - games - blog posts
description: Search page for Rangerrom.com and blog posts.
---

<script src="/js/search.min.js" type="text/javascript" charset="utf-8"></script>

_config.yml
gems: ['jekyll-lunr-js-search']

Gemfile
gem 'jekyll-lunr-js-search'

When I run Jekyll build, I see three files
/js/index.json
/lunr.min.js
/search.min.js

I also have a search result on my home page:
index.html
<div id="search">
  <form action="/search/index.html" method="get">
    <input type="text" id="search-query" name="q" placeholder="Search" autocomplete="off">
  </form>
</div>

However, when I type in the form, I get no result. I see a network issue (logged a separate issue). However, I also notice the .js files generated does not include the mustache template.

Here is my files on gist. I am not sure what exactly I am doing wrong, probably missed something somewhere.

https://gist.github.com/Romiko/f22274490b56bf1bffa3

**Comment by slashdotdash** [comment]
@Romiko It looks as though you need to include the search results template in the `Home.html` file linked in your Gist. Just copy and paste the following example... 

```html
{% raw %}
<script id="search-results-template" type="text/mustache">
  {{#entries}}
    <article>
      <h3>
        {{#date}}<small><time datetime="{{pubdate}}" pubdate>{{displaydate}}</time></small>{{/date}}
        <a href="{{url}}">{{title}}</a></h3>
    </article>
  {{/entries}}
</script>
{% endraw %}
````

**Comment by Romiko** [comment]
Hi Ben,

Much appreciated for the reply. I updated the site and it seems to not
work. Is it possible you can be kind enough to have a look at:

http://rangerrom.com/search/

If you use the developer tools, it looks as if it cannot load a file.


​


On Sat, Jan 10, 2015 at 9:16 AM, Ben Smith <notifications@github.com> wrote:

> @Romiko <https://github.com/Romiko> It looks as though you need to
> include the search results template in the Home.html file linked in your
> Gist. Just copy and paste the following example...
>
> {% raw %}
> <script id="search-results-template" type="text/mustache">
>   {{#entries}}
>     <article>
>       <h3>
>         {{#date}}<small><time datetime="{{pubdate}}" pubdate>{{displaydate}}</time></small>{{/date}}
>         <a href="{{url}}">{{title}}</a></h3>
>     </article>
>   {{/entries}}
> </script>
> {% endraw %}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/slashdotdash/jekyll-lunr-js-search/issues/52#issuecomment-69408508>
> .
>



-- 
Romiko Derbynew
*Mobile:* +61 4000 90251
*Email:* romikov@gmail.com

*Website: *http://rangerrom.com
*Blog: *http://rangerrom.com/blog

**Comment by blimey85** [comment]
You posted this months ago so not sure if you are still interested, but I went ahead and looked into it just in case.

In developer tools I don't see where it's loading your ```index.json``` file. Also, your ```application.js``` file has issues. When you pull it up directly, you'll see it ends with ```{t=jQuery("``` which obviously ins't valid. I initially tried to run it through an UnMinify script so I could read it but that of course didn't work as the rest of your file is missing.
