### ISSUE TITLE
Don't fail confusingly on unsupported Ruby (<2.0)

### ISSUE THREAD

**Issue by hdgarrood** [slashdotdash/jekyll-lunr-js-search#55]
Refs #49. I think the best way to achieve this is:

* Add a note to the README
* Add a runtime check in the actual code before generating the index

If you're happy with this I'll put a PR together.

**Comment by hdgarrood** [comment]
see: http://www.jeffduckett.com/blog/530d34dc62756c5cd0000000/ruby-2-0---new-kernel-method-__dir__.html (cheers @jsuter)

**Comment by slashdotdash** [comment]
Fixed by 2e44de4b0e8be3aa6a0d944eb87c3c0618f2daa6

**Comment by hdgarrood** [comment]
Thanks! :)
