### ISSUE TITLE
Support for Russian language

### ISSUE THREAD

**Issue by iloveip** [slashdotdash/jekyll-lunr-js-search#58]
Hello,

Does this plugin support Russian language?

**Comment by slashdotdash** [comment]
@iloveip The plugin uses [lunr.js](http://lunrjs.com/) for the actual searching functionality and it only supports English. It looks as though it could be made to work with other languages. You would need to investigate how to do so.

**Comment by iloveip** [comment]
Ok, thank you very much.

**Comment by kojoru** [comment]
Hi @iloveip 

Just for your information I hacked up a version compatible with Russian language: https://github.com/kojoru/jekyll-lunr-js-search/tree/i18n

I am currenlty working on a solution that will allow users to select language cleanly via config. Meanwhile the hacked-together version works nicely on a production site.

**Comment by iloveip** [comment]
Hi @kojoru 

Thank you very much! I'm actually trying to install this plugin from your branch. But I have some problems. I do it manually. Could you please explain which files exactly I have to copy and where. (I tried to install it as a gem, but unfortunately it didn't work for me.)
