### ISSUE TITLE
errors with gems in installing -- "`require': cannot load such file -- jekyll-lunr-js-search (LoadError)"

### ISSUE THREAD

**Issue by tomjohnson1492** [slashdotdash/jekyll-lunr-js-search#65]
When I try to install this plugin using the gem method, I get this error: 

```
^Ctjohnson-mbpr13:resolve tjohnson$ gem install jekyll-lunr-js-search
Successfully installed jekyll-lunr-js-search-0.2.1
Parsing documentation for jekyll-lunr-js-search-0.2.1
1 gem installed
tjohnson-mbpr13:resolve tjohnson$ jekyll serve
Configuration file: /Users/tjohnson/projects/resolve/_config.yml
/Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- jekyll-lunr-js-search (LoadError)
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/bin/jekyll:23:in `load'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/bin/jekyll:23:in `<main>'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `<main>'
```

I'm not if there are certain dependencies required that I don't have?

**Comment by blimey85** [comment]
In your ```_config.yml``` do you have the following:

```
gems:
  - jekyll-lunr-js-search
```
For my installation I added it to my ```Gemfile```, ran ```bundle install``` and then added it to my ```_config.yml```. Installing it on the command line will work the same. Just added it to your ```_config.yml``` and you'll be good to go.

**Comment by Yan1** [comment]
when I generation the project, this error come up:

Configuration file: F:/work/jekyll/app/_config.yml
C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
: cannot load such file -- v8 (LoadError)
        from C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from F:/work/jekyll/app/_plugins/jekyll_lunr_js_search.rb:5:in `<top (re
quired)>'
        from C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plug
in_manager.rb:74:in `block (2 levels) in require_plugin_files'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plug
in_manager.rb:73:in `each'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plug
in_manager.rb:73:in `block in require_plugin_files'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plug
in_manager.rb:72:in `each'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plug
in_manager.rb:72:in `require_plugin_files'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plug
in_manager.rb:18:in `conscientious_require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site
.rb:79:in `setup'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site
.rb:41:in `initialize'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/comm
ands/build.rb:29:in `new'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/comm
ands/build.rb:29:in `process'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/comm
ands/serve.rb:26:in `block (2 levels) in init_with_program'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `call'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `block in execute'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `each'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `execute'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenar
y/program.rb:42:in `go'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenar
y.rb:19:in `program'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/bin/jekyll:20:i
n `<top (required)>'
        from C:/Ruby21-x64/bin/jekyll:23:in `load'
        from C:/Ruby21-x64/bin/jekyll:23:in `<main>'

**Comment by slashdotdash** [comment]
If you are using the gem and it is installed, ensure you have included it in your Jekyll site's config file.

_config.yml

    gems: ['jekyll-lunr-js-search']
