### ISSUE TITLE
any plans to update this plugin to work with the latest version of jekyll?

### ISSUE THREAD

**Issue by tomjohnson1492** [slashdotdash/jekyll-lunr-js-search#67]
I just wanted to know if there are any plans to update this plugin to work with the latest version of jekyll? The gem doesn't seem to be compatible, nor the plugin. Yet this plugin seems pretty critical for websites.

**Comment by blimey85** [comment]
When you say not compatible, what errors are you getting? Or is it just not working rather than throwing any errors?

**Comment by slashdotdash** [comment]
I've just pushed an update to support latest version of Jekyll (v3).

### Jekyll 2

Use [jekyll-lunr-js-search 2.0.0](https://rubygems.org/gems/jekyll-lunr-js-search/versions/2.0.0)
    
    gem install jekyll-lunr-js-search -v2.0.0

### Jekyll 3 

Use [jekyll-lunr-js-search 3.0.0](https://rubygems.org/gems/jekyll-lunr-js-search/versions/3.0.0)

    gem install jekyll-lunr-js-search -v3.0.0
