### ISSUE TITLE
Can it work with github server

### ISSUE THREAD

**Issue by samuel1208** [slashdotdash/jekyll-lunr-js-search#68]
I follow your configuration. And It can work locally (generated by jekyll server). But we I upload my blog onto github .  It can't work anymore. Did I do anything wrong

**Comment by bcawrse** [comment]
I read on the Jekyll website that Github disables Jekyll plugins. That's probably the issue, move the static files?

http://jekyllrb.com/docs/plugins/

>GitHub Pages is powered by Jekyll. However, all Pages sites are generated using the --safe option to disable custom plugins for security reasons. Unfortunately, this means your plugins won’t work if you’re deploying to GitHub Pages.

>You can still use GitHub Pages to publish your site, but you’ll need to convert the site locally and push the generated static files to your GitHub repository instead of the Jekyll source files.

**Comment by slashdotdash** [comment]
Yes, the plugin is disabled on GitHub pages. Instead you must build the pages locally and push the result files, instead of the source files.
