### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by ccsastro** [slashdotdash/jekyll-lunr-js-search#74]
My search works in English but not Japanese. The index.json file has Japanese entries, but the search doesn't return anything when searching for Japanese strings. Can anyone reproduce this and/or suggest a fix?

**Comment by slashdotdash** [comment]
The underlying search library, [lunr.js](http://lunrjs.com/), only supports English. So unfortunately you will not be able to search with Japanese text.

**Comment by ccsastro** [comment]
Ah, ok, thanks for the info.
