### ISSUE TITLE
Display matching line or context?

### ISSUE THREAD

**Issue by blay** [slashdotdash/jekyll-lunr-js-search#79]
This may be outside of the scope of this plugin and more of a feature request, but would it be possible with the current tools set (lunr.js) to display the matching line from the blog post content in the search results or some context around the match (5 words before and after for example).

/Magnus

**Comment by slashdotdash** [comment]
The [lunr.js](http://lunrjs.com/) library doesn't have support for search context. It only returns matching documents and their score.

There's an open feature request for exactly that feature for lunr.js, but it doesn't look like it will be implemented.

- [Highlighted matched terms](https://github.com/olivernn/lunr.js/issues/25)
