### ISSUE TITLE
Ignoring layout contents when generating index

### ISSUE THREAD

**Issue by djfdev** [slashdotdash/jekyll-lunr-js-search#81]
I have a lengthy sidebar on my site, which appears on every page (it is contained in my default layout). When I search for an item that is in the sidebar, my search results contain every page of my site. This makes my search bar fairly useless.

Is there any way to ignore layouts when indexing? It would be great if I could run lunr before Jekyll renders the HTML. I tried adding the `exclude_from_search` flag to my default.html file, but that doesn't seem to fix the issue.

**Comment by kidk** [comment]
This would be handy. I'm researching it at the moment and I've found where I might be able to remove certain parts of the page from indexing. But I don't know yet what the best method is to do so.

**Comment by slashdotdash** [comment]
I've just pushed a fix for this issue (#1c921358b4a9ee0a49effaaa48c738f60b6550e6).

Please upgrade your version of the jekyll-lunr-js-search gem to **v3.0.0**

    gem install jekyll-lunr-js-search -v3.0.0
