### ISSUE TITLE
Enabling search on github pages

### ISSUE THREAD

**Issue by banesto** [slashdotdash/jekyll-lunr-js-search#82]
This is a great plugin, but I'm strugling with getting it to work on gh-pages. I've triet putting in git _sites folder but that solution was not working due to js files not being loaded (json or lunr), if I change 
```
js_dir: "../js"
```
then it's working, but at some point I've got a indefinate loop of reindexing when running ```jekyll serve --watch``` which burns my cpu.

What are best advised options get search working on gh-pages?

**Comment by slashdotdash** [comment]
GitHub pages runs Jekyll in safe mode which disables all plugins. 

For this search plugin to work you would need to Jekyll locally, with the plugin installed, to generate the content and then push the generated files to your GitHub repository.

http://jekyllrb.com/docs/plugins/

> GitHub Pages is powered by Jekyll. However, all Pages sites are generated using the --safe option to disable custom plugins for security reasons. Unfortunately, this means your plugins won’t work if you’re deploying to GitHub Pages.

> You can still use GitHub Pages to publish your site, but you’ll need to convert the site locally and push the generated static files to your GitHub repository instead of the Jekyll source files.

**Comment by xHN35RQ** [comment]
Try this if you want full text search on Github Pages: https://github.com/xHN35RQ/jekyll-tipue-search
