### ISSUE TITLE
Working with other languages

### ISSUE THREAD

**Issue by pozitron57** [slashdotdash/jekyll-lunr-js-search#84]
I managed to get this plugin working with Octopress and tested it locally. It came out that search engine works only with English letters and don't with Cyrillic ones. Should it be like this or I did something wrong?

`index.json` contains Russian words but only English queries work. It is a pity because plugin is very nice!

**Comment by slashdotdash** [comment]
The lunr.js JavaScript library that provides the search capability only has support for English language. Support for other languages is therefore dependent upon that library adding support.
