### ISSUE TITLE
date not showing

### ISSUE THREAD

**Issue by goessni** [slashdotdash/jekyll-lunr-js-search#88]
Hello,

with Jekyll v3.0.1, there is no date shown in the search results. Neither {{pubdate}} nor {{displaydate}} shows up. I did test it with a blog I develop, and a standard vanilla install. Any idea where to look for the problem?

Thanks in advance,
Clemens

**Comment by dauryg** [comment]
Ran into this issue myself. submitted a [pull request](https://github.com/slashdotdash/jekyll-lunr-js-search/pull/89).

**Comment by goessni** [comment]
Perfect, thanks!

**Comment by dauryg** [comment]
I think you would have to look into lunarjs side of things. You can add a custom function into the pipeline to change the way it indexes/sorts. http://lunrjs.com/docs/#Pipeline

**Comment by ttimsmith** [comment]
I hope that PR is merged soon. I'm running into this issue too
